name: Build C++ (MSVC) x86

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-win32:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSVC Environment
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 'latest'

      - name: Create build directory
        run: |
          if not exist build mkdir build

      - name: Configure CMake
        working-directory: build
        run: |
          cmake .. -G "Visual Studio 17 2022" -A Win32

      - name: Build solution
        working-directory: build
        run: |
          cmake --build . --config Release

      - name: Upload DLL artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dll-artifacts
          path: |
            build/Release/backend.dll
            build/Release/vefxio.dll
            build/Release/eamio.dll
