name: Build C++ (MSVC) x86

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-win32:
    runs-on: windows-latest

    env:
      VCPKG_DEFAULT_TRIPLET: x86-windows-static

    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Restore from cache and setup vcpkg executable and data files.
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'
          runVcpkgInstall: true

      - name: Run CMake+vcpkg+Ninja to build packages and generate/build the code.
        uses: lukka/run-cmake@v10
        with:
          configurePreset: x86-release

      - name: Upload DLL artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dll-artifacts
          path: |
            backend.dll
            vefxio.dll
            eamio.dll
